---
- name: Rm file
  ansible.builtin.command: rm -rf .kube/*
  changed_when: true

- name: Cp file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: '0600'
    remote_src: true

- name: Chown file
  ansible.builtin.command: "chown root:root /root/.kube/config"
  changed_when: true
