- name: Install Metricbeat
  ansible.builtin.command: sudo rpm -vi /tmp/metricbeat/metricbeat-8.12.1-x86_64.rpm

- name: Create metricbeat.yml file
  ansible.builtin.template:
    src: /root/playbook-raot/roles/Metricbeat/templates/metricbeat.yml.j2 
    dest: /etc/metricbeat/metricbeat.yml
    mode: '755'

- name: Create system.yml file
  ansible.builtin.template:
    src: /root/playbook-raot/roles/Metricbeat/templates/system.yml.j2
    dest: /etc/metricbeat/modules.d/system.yml
    mode: '755'

- name: Check modules system
  ansible.builtin.command: "metricbeat modules list | grep system"
  register: moduleslist

- name: Debug modules list
  ansible.builtin.debug:
    var: moduleslist.stdout_lines

# - name: Check port service logstash
#   ansible.builtin.shell: "netstat -auptn | grep {{ portlogstash }}"

- name: Start and enabled service Metricbeat
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: true

- name: Check status service Metricbeat
  ansible.builtin.systemd:
    name: metricbeat
  register: statusmetricbeat

- name: Debug status service metricbeat
  ansible.builtin.debug:
    var: statusmetricbeat.status.ActiveState