- name: Prerequisite software the lastest version
  ansible.builtin.yum:
    name: 
    - perl-Digest-SHA 
    - telnet
    - net-tools 
    state: latest

- name: Make diectory for file install metricbeat
  ansible.builtin.file:
      path: /tmp/metricbeat/
      state: directory
      mode: '0755'

- name: Scp file install Metricbeat Package version 8.12.1 to all nodes
  ansible.builtin.copy:
    src: /root/playbook-raot/roles/Metricbeat/templates/metricbeat-8.12.1-x86_64.rpm
    dest: /tmp/metricbeat/metricbeat-8.12.1-x86_64.rpm
    owner: root
    group: root
    mode: '0644'

- name: SHA Checksums
  ansible.builtin.shell:
    cmd:  shasum -a 512 /tmp/metricbeat/metricbeat-8.12.1-x86_64.rpm

